FROM:
C:\SDL2\x86_64-w64-mingw32\include\SDL2

TO:
C:\MinGW\include\SDL2

C:\MinGW\include\SDL2\SDL.h   

C:\SDL2\x86_64-w64-mingw32\lib\* 
→ C:\MinGW\lib\

C:\SDL2_ttf\x86_64-w64-mingw32\lib\*
→ C:\MinGW\lib\


C:\SDL2\x86_64-w64-mingw32\bin\SDL2.dll
C:\SDL2_ttf\x86_64-w64-mingw32\bin\SDL2_ttf.dll
→ project folder (Traffic Light)
